sonar.projectKey=com.projetfilrouge:loanmanagement
sonar.projectName=Loan Management API
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**
