package com.projetfilrouge.loanmanagement.entity;

public enum LoanApplicationEventType {
    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,
    DOCUMENT_UPLOADED,
    ADVISOR_ASSIGNED,
    REVIEW_STARTED,
    DOCUMENT_REJECTED,
    DOCUMENT_VALIDATED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_CANCELLED,
    FUNDS_RELEASED
}
