package com.projetfilrouge.loanmanagement.entity;

public enum LoanApplicationEventType {
    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,
    DOCUMENT_UPLOADED,
    ADVISOR_ASSIGNED,
    REVIEW_STARTED,
    DOCUMENT_REJECTED,
    DOCUMENT_VALIDATED,
    OFFER_PROPOSED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_CANCELLED,
    FUNDS_RELEASED,
    LOAN_CREATED,
    MANDATE_ACTIVATED,
    MANDATE_REVOKED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    INSTALLMENT_OVERDUE,
    LOAN_CLOSED,
    LOAN_DEFAULTED
}
